services:
  busybox:
    restart: unless-stopped
    image: busybox
    container_name: busy
    labels:
      - "maestro.enable=true"
      - "maestro.tags=nfs_mount,server"
      - "maestro.priority=900"
      - "maestro.hosts=server,vm"
