services:
  my-app-1:
    restart: unless-stopped
    image: busybox
    container_name: my-app-1
    command: sleep infinity
    labels:
      - "maestro.enable=true"
      - "maestro.tags=compute_intensive,test"
      - "maestro.priority=800"
      - "maestro.hosts=server,vm"

  my-app-2:
    restart: unless-stopped
    image: busybox
    container_name: my-app-2
    command: sleep infinity
    labels:
      - "maestro.enable=true"
      - "maestro.tags=test,gpu"
      - "maestro.priority=500"
      - "maestro.hosts=server,vm"

  my-app-3:
    restart: unless-stopped
    image: busybox
    container_name: my-app-3
    command: sleep infinity
    labels:
      - "maestro.enable=true"
      - "maestro.tags=test,cicd"
      - "maestro.priority=10"
      - "maestro.hosts=server,vm"
